version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ionic/storage"
    versions:
    - 2.3.1
    - 3.0.2
  - dependency-name: cordova-ios
    versions:
    - 6.1.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
